# services:
#   nginx-demo:
#     image: nginx:1.17.10
#     ports:
#       - "80:80"
#       - "433:433"
#       - "3000:3000"
#     volumes:
#       - ./AirmailGPT-Nginx/nginx.conf:/etc/nginx/nginx.conf
#       - ./AirmailGPT-Nginx/ssl:/etc/nginx/ssl
#     depends_on:
#       # - api-demo
#       # - nodejs-demo
#       - client-demo
#       # - db-demo

#   # api-demo:
#   #   build: ./AirmailGPT-API
#   #   expose:
#   #     - "8080"

#   # nodejs-demo:
#   #   build: ./AirmailGPT-NodeJS
#   #   expose:
#   #     - "4000"

#   client-demo:
#     build: ./AirmailGPT-Client/airmail_gpt_client

#   # db-demo:
#   #   build: ./AirmailGPT-DB
#   #   expose:
#   #     - "3306"


services:
  api:
    build:
      context: ./AirmailGPT-API
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    expose:
      - "8080"
    # environment:
    #   - SPRING_PROFILES_ACTIVE=prod
    networks:
      - airmail-network
    # container_name: api

  # nodejs:
  #   build:
  #     context: ./AirmailGPT-NodeJS
  #     dockerfile: Dockerfile
  # #   # ports:
  # #   #   - "3000:3000"
  #   expose:
  #     - "3000"
  #   networks:
  #     - airmail-network
  # #   container_name: nodejs

  client:
    build:
      context: ./AirmailGPT-Client/airmail_gpt_client
      dockerfile: Dockerfile
    # ports:
    #   - "80:80"
    expose:
      - "80"
    networks:
      - airmail-network
    # container_name: client

  nginx:
    image: nginx:1.17.10
    volumes:
      - ./AirmailGPT-Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./AirmailGPT-Nginx/conf.d:/etc/nginx/conf.d
      - ./AirmailGPT-Nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "8443:8443"
    networks:
      - airmail-network
    depends_on:
      - api
      # - nodejs
      - client

networks:
  airmail-network:
    driver: bridge