services:
  api:
    build:
      context: ./AirmailGPT-API
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - airmail-network
    
  # nodejs:
  #   build:
  #     context: ./AirmailGPT-NodeJS
  #     dockerfile: Dockerfile
  # #   # ports:
  # #   #   - "3000:3000"
  #   expose:
  #     - "3000"
  #   networks:
  #     - airmail-network
  # #   container_name: nodejs

  client:
    build:
      context: ./AirmailGPT-Client/airmail_gpt_client
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - airmail-network
    depends_on:
      - api
      # - nodejs

  nginx:
    image: nginx:1.17.10
    volumes:
      - ./AirmailGPT-Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./AirmailGPT-Nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "81:80"
    networks:
      - airmail-network
    depends_on:
      - api
      # - nodejs
      - client

networks:
  airmail-network:
    driver: bridge