// const String airmanName = 'AIRMAN_NAME';
// const String airmanBirth = 'AIRMAN_BIRTH';
// const String constantApiDomain = 'API_DOMAIN';
// const String constantSenderZipcode = 'SENDER_ZIPCODE';
// const String constantSenderAddress1 = 'SENDER_ADDRESS1';
// const String constantSenderAddress2 = 'AirmailGPT for ROKAF';
// final DateTime constantBootcampEndDate = DateTime(2023, 5, 26, 11, 0, 0);
// final DateTime constantMailStartDate = DateTime(2023, 5, 10, 9, 0, 0);
// final DateTime constantMailEndDate = DateTime(2023, 5, 24, 17, 0, 0);